version: "3.9"

services:
  user-service:
    build:
      context: ./user-service
    ports:
      - "5001:5001"

  notification-service:
    build:
      context: ./notification-service
    ports:
      - "5003:5003"

  menu-service:
    build:
      context: ./menu-service
    ports:
      - "5002:5001"  # Ensure this line has proper indentation
    environment:
      - DATABASE_URI=mongodb://mongo:27017/foodapp
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
